---
- hosts: all
  become: yes
  vars: 
    packages: ["lsof", "wget", "passwd", "docker", "unzip", "java-17*"]
  tasks:
    - name: Install packages on RedHat family
      yum:
        name: "{{ item }}"
        state: latest
      loop: "{{ packages }}"
      when: ansible_os_family == "RedHat"

    - name: Start Docker daemon on RedHat family
      service:
        name: docker
        state: started
        enabled: yes
      when: ansible_os_family == "RedHat"

    - name: Install packages on Ubuntu family
      apt:
        name: "{{ item }}"
        state: latest
      loop: "{{ packages }}"
      when: ansible_os_family == "Debian"

    - name: Start Docker daemon on Ubuntu family
      service:
        name: docker
        state: started
        enabled: yes
      when: ansible_os_family == "Debian"
